CREATE DATABASE TUGAS_BUTKEM

USE TUGAS_BUTKEM


CREATE TABLE Users (
	UserID VARCHAR(20),
	FirstName VARCHAR(100),
	LastName VARCHAR(100),
	School VARCHAR(150),
	Email VARCHAR(150),
	PhoneNum INT,
	Locationn VARCHAR(100),
	DateOfBirth VARCHAR(10),
	Gender VARCHAR(10),
	CONSTRAINT UserPK PRIMARY KEY (UserId)
)

CREATE TABLE Friends (
	UserID VARCHAR(20) FOREIGN KEY REFERENCEs Users(UserID),
	FriendID CHAR(20)
)

CREATE TABLE Pages(
	PageID VARCHAR (20),
	PageName VARCHAR(100),
	PageContent VARCHAR(100),
	CONSTRAINT PagePK PRIMARY KEY (PageID)
)

CREATE TABLE PagesLikes (
	PageID VARCHAR(20) FOREIGN KEY REFERENCES Pages(PageID),
	UserID VARCHAR(20) FOREIGN KEY REFERENCES Users(UserID)
)

CREATE TABLE Posts (
	PostID CHAR(20),
	UserID VARCHAR(20),
	CONSTRAINT PostPK PRIMARY KEY (PostID)
)

CREATE TABLE PostLikes (
	PostID CHAR(20) FOREIGN KEY REFERENCES Posts(PostID),
	UserID VARCHAR(20),
)

CREATE TABLE Photos (
	PostID CHAR(20) FOREIGN KEY REFERENCES Posts(PostID),
	UserID VARCHAR(20),
	ImageContent VARCHAR(200)
)

CREATE TABLE Shares (
	PostID CHAR(20) FOREIGN KEY REFERENCES Posts(PostID),
	UserID VARCHAR(20)
)

CREATE TABLE Comments (
	CommentID VARCHAR(20),
	PostID CHAR(20) FOREIGN KEY REFERENCES Posts(PostID),
	UserID VARCHAR(20),
	CommentContent VARCHAR(200),
	CommentDate VARCHAR(20),
	CONSTRAINT CommentPK PRIMARY KEY (CommentID)
)

CREATE TABLE CommentLikes(
	CommentID VARCHAR(20) FOREIGN KEY REFERENCES Comments(CommentID),
	UserID VARCHAR(20)
)
